"""MapResponse v2 — the contract between the Atlas BFF and its independent guide.

The imported v2 contract is preserved: version tag, richer markers,
route_meta, itinerary, sources, warnings. Coordinates are always {lat, lng} objects.

Rule: coordinates outside the Jeju bbox are *rejected* — dropped from the response and reported in `warnings`.
Route geometry note: out-of-bbox `route` points are dropped **individually** and the remaining points are joined,
so a polyline that legitimately leaves the bbox comes back re-stitched (a straight shortcut) rather than rejected.
Inside this product's scope every route stays on Jeju, and a consumer that needs the original geometry must treat
a `route[i] outside Jeju bbox` warning as "this polyline was altered".

Size caps: `answer` ≤ MAX_ANSWER_CHARS, `markers` ≤ MAX_MARKERS_V2, `route` ≤ MAX_ROUTE_POINTS,
`warnings` ≤ MAX_WARNINGS — one agent reply must not be able to build an arbitrarily large `map` event.
`MarkerV2.url` is limited to http/https (anything else, `javascript:` included, becomes None): renderers link it.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator, model_validator

JEJU_BBOX = {"lat": (33.10, 33.60), "lng": (126.15, 126.98)}
MAX_MARKERS_V2 = 12
MAX_MARKERS_V1 = 8
MAX_ANSWER_CHARS = 4000
MAX_ROUTE_POINTS = 512
MAX_WARNINGS = 32
FALLBACK_ANSWER = "죄송합니다. 답변을 생성하지 못했습니다. 다시 질문해 주세요."
SAFE_URL_SCHEMES = ("http://", "https://")

# `warnings` carries both agent-supplied strings and strings this layer (or the BFF) generated. They travel in one
# array by design — the renderer decides what to show — so a consumer that must tell them apart uses
# is_server_warning() instead of matching literals of its own.
LENIENT_PARSE_WARNING = "lenient_parse"
ANSWER_ONLY_WARNING = "answer_only"
MAP_MISSING_WARNING = "map_missing"  # appended by the Atlas BFF when no map event arrived
SERVER_WARNING_CODES = (LENIENT_PARSE_WARNING, ANSWER_ONLY_WARNING, MAP_MISSING_WARNING)
_SERVER_WARNING_PREFIXES = ("center outside Jeju bbox", "marker ", "route[", "itinerary.days[")


def is_server_warning(warning: str) -> bool:
    """True for a warning generated by this contract layer or the BFF (bbox rejection, parse fallbacks).

    Anything else came from the agent and is free-form text; treat it as untrusted content when rendering.
    """
    return warning in SERVER_WARNING_CODES or warning.startswith(_SERVER_WARNING_PREFIXES)


RouteMode = Literal["car", "walk", "transit", "straight"]
_HHMM_RE = re.compile(r"^([01]\d|2[0-3]):[0-5]\d$")
_DATE_RE = re.compile(r"^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$")
_FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL)


def in_jeju_bbox(lat: float, lng: float) -> bool:
    return JEJU_BBOX["lat"][0] <= lat <= JEJU_BBOX["lat"][1] and JEJU_BBOX["lng"][0] <= lng <= JEJU_BBOX["lng"][1]


def _iso8601_or_none(value: str | None) -> str | None:
    if value is None:
        return None
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(f"observed_at must be ISO 8601: {value!r}") from exc
    return value


class LatLng(BaseModel):
    model_config = ConfigDict(extra="ignore")
    lat: float = Field(ge=-90, le=90)
    lng: float = Field(ge=-180, le=180)


class MarkerV2(LatLng):
    id: str = Field(min_length=1)
    name: str = Field(min_length=1)
    category: str = Field(min_length=1)
    summary: str = ""
    source: str | None = None
    observed_at: str | None = None
    url: str | None = None
    phone: str | None = None
    hours: str | None = None
    distance_m: int | None = Field(default=None, ge=0)

    @field_validator("observed_at")
    @classmethod
    def _observed_at_iso(cls, v: str | None) -> str | None:
        return _iso8601_or_none(v)

    @field_validator("url")
    @classmethod
    def _url_http_only(cls, v: str | None) -> str | None:
        """Keep only http/https links. A marker with a `javascript:`/`data:`/relative url keeps everything but
        the link (dropping the whole marker would lose a real POI over a bad field). CSP blocks such a
        navigation today; the contract must not depend on that."""
        if v is None:
            return None
        v = v.strip()
        return v if v.lower().startswith(SAFE_URL_SCHEMES) else None


class RouteMeta(BaseModel):
    model_config = ConfigDict(extra="ignore")
    mode: RouteMode
    distance_m: int = Field(ge=0)
    duration_s: int | None = Field(default=None, ge=0)
    provider: str = Field(min_length=1)


class Stop(LatLng):
    id: str = Field(min_length=1)
    name: str = Field(min_length=1)
    arrive: str | None = None
    stay_min: int | None = Field(default=None, ge=0)
    note: str | None = None

    @field_validator("arrive")
    @classmethod
    def _arrive_hhmm(cls, v: str | None) -> str | None:
        if v is not None and not _HHMM_RE.match(v):
            raise ValueError(f"arrive must be HH:MM: {v!r}")
        return v


class Leg(BaseModel):
    model_config = ConfigDict(extra="ignore")
    from_id: str = Field(min_length=1)
    to_id: str = Field(min_length=1)
    distance_m: int = Field(ge=0)
    duration_s: int | None = Field(default=None, ge=0)
    mode: RouteMode = "car"


class ItineraryDay(BaseModel):
    """`legs` is intentionally NOT pruned when bbox rejection drops a stop it references.

    Contract: MapResponseV2's bbox rejection removes out-of-Jeju `stops` but leaves `legs`
    untouched, so a leg's `from_id`/`to_id` can end up pointing at a stop id no longer present
    in `stops` (a dangling reference) — this is deliberate (mandated by
    tests/product/test_contracts.py::test_itinerary_stops_outside_bbox_are_dropped_and_helper_reports_them,
    which asserts legs survive stop removal) rather than an oversight. No coordinates leak this
    way — the bbox-outside stop's lat/lng are gone, only its id/name survive inside the leg and
    inside `warnings` — so the 100% bbox-rejection SLO still holds. Consumers that render or sum
    `legs` (itinerary renderer, distance totals, the JSON Schema in Task 3, the TS guards in
    Task 4) MUST look up each `from_id`/`to_id` against `stops` and skip/flag a leg whose
    endpoint is missing, rather than assume every leg's endpoints resolve.
    """

    model_config = ConfigDict(extra="ignore")
    date: str | None = None
    stops: list[Stop] = Field(default_factory=list)
    legs: list[Leg] = Field(default_factory=list)

    @field_validator("date")
    @classmethod
    def _date_iso(cls, v: str | None) -> str | None:
        if v is not None and not _DATE_RE.match(v):
            raise ValueError(f"date must be YYYY-MM-DD: {v!r}")
        return v


class Itinerary(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str = Field(min_length=1)
    days: list[ItineraryDay] = Field(default_factory=list)


class Source(BaseModel):
    model_config = ConfigDict(extra="ignore")
    provider: str = Field(min_length=1)
    label: str = Field(min_length=1)
    observed_at: str | None = None

    @field_validator("observed_at")
    @classmethod
    def _observed_at_iso(cls, v: str | None) -> str | None:
        return _iso8601_or_none(v)


def itinerary_bbox_warnings(itinerary: Itinerary) -> list[str]:
    """Warnings for itinerary stops outside Jeju (does not mutate; MapResponseV2 uses the same wording)."""
    warns: list[str] = []
    for d, day in enumerate(itinerary.days):
        for s in day.stops:
            if not in_jeju_bbox(s.lat, s.lng):
                warns.append(f"itinerary.days[{d}] stop {s.id} ({s.name}) outside Jeju bbox: ({s.lat}, {s.lng})")
    return warns


class MapResponseV2(BaseModel):
    """answer: 한국어 3~5문장(또는 locale=en 영어). zoom: 웹 머카토르(제주 전체 ≈ 10). markers: 최대 12개."""

    model_config = ConfigDict(extra="ignore")
    version: Literal["2"] = "2"
    answer: str = Field(min_length=1, max_length=MAX_ANSWER_CHARS)
    center: LatLng | None = None
    zoom: int = Field(default=10, ge=1, le=20)
    markers: list[MarkerV2] = Field(default_factory=list, max_length=MAX_MARKERS_V2)
    route: list[LatLng] = Field(default_factory=list, max_length=MAX_ROUTE_POINTS)
    route_meta: RouteMeta | None = None
    itinerary: Itinerary | None = None
    sources: list[Source] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list, max_length=MAX_WARNINGS)

    @field_validator("answer")
    @classmethod
    def _answer_not_blank(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("answer must not be blank")
        return v

    @model_validator(mode="after")
    def _reject_outside_jeju(self) -> "MapResponseV2":
        warns: list[str] = []
        if self.center is not None and not in_jeju_bbox(self.center.lat, self.center.lng):
            warns.append(f"center outside Jeju bbox: ({self.center.lat}, {self.center.lng})")
            self.center = None
        kept: list[MarkerV2] = []
        for m in self.markers:
            if in_jeju_bbox(m.lat, m.lng):
                kept.append(m)
            else:
                warns.append(f"marker {m.id} ({m.name}) outside Jeju bbox: ({m.lat}, {m.lng})")
        self.markers = kept
        route: list[LatLng] = []
        for i, pt in enumerate(self.route):
            if in_jeju_bbox(pt.lat, pt.lng):
                route.append(pt)
            else:
                warns.append(f"route[{i}] outside Jeju bbox: ({pt.lat}, {pt.lng})")
        self.route = route
        if self.itinerary is not None:
            # pydantic v2 keeps a shared reference when a caller passes an already-built
            # Itinerary instance (model_config default: revalidate_instances="never").
            # Deep-copy before mutating nested ItineraryDay.stops so we never rewrite the
            # caller's own object out from under it.
            self.itinerary = self.itinerary.model_copy(deep=True)
            warns.extend(itinerary_bbox_warnings(self.itinerary))
            for day in self.itinerary.days:
                # legs are left untouched on purpose — see ItineraryDay docstring (dangling
                # from_id/to_id contract).
                day.stops = [s for s in day.stops if in_jeju_bbox(s.lat, s.lng)]
        if warns:
            # Truncate: 12 markers + 512 route points outside the bbox would otherwise produce hundreds of
            # warnings. Field(max_length=…) does not apply to assignment, so cap it here.
            self.warnings = [*self.warnings, *warns][:MAX_WARNINGS]
        return self


_V1_MARKER_KEYS = ("id", "name", "lat", "lng", "category", "summary")


def to_v1(resp: MapResponseV2) -> dict[str, Any]:
    """Project onto the frozen v1 contract: answer/center/zoom/markers[<=8, v1 keys only]/route."""
    return {
        "answer": resp.answer,
        "center": resp.center.model_dump() if resp.center else None,
        "zoom": resp.zoom,
        "markers": [{k: getattr(m, k) for k in _V1_MARKER_KEYS} for m in resp.markers[:MAX_MARKERS_V1]],
        "route": [p.model_dump() for p in resp.route],
    }


def _candidate_json_blobs(text: str) -> list[str]:
    blobs = [text.strip()]
    blobs += _FENCE_RE.findall(text)
    first, last = text.find("{"), text.rfind("}")
    if first != -1 and last > first:
        blobs.append(text[first : last + 1])
    return blobs


def _validate_each(model: type[BaseModel], items: Any) -> list[Any]:
    out: list[Any] = []
    for raw in items if isinstance(items, list) else []:
        try:
            out.append(model.model_validate(raw))
        except (ValidationError, TypeError):
            continue
    return out


def _validate_optional(model: type[BaseModel], raw: Any) -> Any:
    if raw is None:
        return None
    try:
        return model.model_validate(raw)
    except (ValidationError, TypeError):
        return None


def _lenient_build(data: dict[str, Any], fallback_answer: str) -> MapResponseV2:
    """Keep every valid part, drop invalid markers/points/blocks, trim markers to 12, tag `lenient_parse`."""
    answer = data.get("answer")
    if not isinstance(answer, str) or not answer.strip():
        answer = fallback_answer
    answer = answer[:MAX_ANSWER_CHARS]
    zoom = data.get("zoom", 10)
    if isinstance(zoom, bool) or not isinstance(zoom, int) or not 1 <= zoom <= 20:
        zoom = 10
    raw_warnings = data.get("warnings")
    warnings = [w for w in raw_warnings if isinstance(w, str)] if isinstance(raw_warnings, list) else []
    return MapResponseV2(
        answer=answer,
        center=_validate_optional(LatLng, data.get("center")),
        zoom=zoom,
        markers=_validate_each(MarkerV2, data.get("markers"))[:MAX_MARKERS_V2],
        route=_validate_each(LatLng, data.get("route"))[:MAX_ROUTE_POINTS],
        route_meta=_validate_optional(RouteMeta, data.get("route_meta")),
        itinerary=_validate_optional(Itinerary, data.get("itinerary")),
        sources=_validate_each(Source, data.get("sources")),
        warnings=[*warnings[: MAX_WARNINGS - 1], LENIENT_PARSE_WARNING],
    )


def parse_map_response_v2(payload: str | dict[str, Any]) -> MapResponseV2:
    """Best-effort parser: strict model → lenient rebuild → fenced/embedded JSON → answer-only text."""
    if isinstance(payload, dict):
        try:
            return MapResponseV2.model_validate(payload)
        except ValidationError:
            return _lenient_build(payload, FALLBACK_ANSWER)
    text = (payload or "").strip()
    fallback_answer = (text or FALLBACK_ANSWER)[:MAX_ANSWER_CHARS]
    for blob in _candidate_json_blobs(text):
        try:
            data = json.loads(blob)
        except (json.JSONDecodeError, TypeError):
            continue
        if not isinstance(data, dict):
            continue
        try:
            return MapResponseV2.model_validate(data)
        except ValidationError:
            return _lenient_build(data, fallback_answer)
    return MapResponseV2(answer=fallback_answer, warnings=[ANSWER_ONLY_WARNING])
